# Generated by Django 3.0.2 on 2020-02-04 03:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0003_auto_20200204_0347'),
        ('mobinfo', '0004_auto_20200204_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PausedNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceOrgNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceOsRah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceUserNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StopNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationsNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumMob', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введіть номер телефону', max_length=128, region=None, unique=True, verbose_name='Номер')),
                ('OsRah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobinfo.OsRah', verbose_name='Особовий рахунок')),
                ('TaxMob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobinfo.TaxMob', verbose_name='Тариф')),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.UserInfo', verbose_name='Абонент')),
            ],
        ),
    ]
