# Generated by Django 3.0.2 on 2020-02-04 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationsnum',
            options={'verbose_name': 'номер для активації', 'verbose_name_plural': 'номери для активації'},
        ),
        migrations.AddField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name=datetime.datetime(2020, 2, 4, 5, 32, 10, 796819)),
            preserve_default=False,
        ),
    ]
