# Generated by Django 3.0.2 on 2020-02-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0002_auto_20200204_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
