# Generated by Django 3.0.2 on 2020-02-04 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0003_auto_20200204_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 4, 5, 36, 37, 876260)),
        ),
    ]
