# Generated by Django 3.0.2 on 2020-02-04 03:38

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0004_auto_20200204_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationsnum',
            name='NumMob',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введіть номер телефону', max_length=128, region=None, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 5, 38, 59, 392271)),
        ),
    ]
