# Generated by Django 3.0.2 on 2020-02-08 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0005_auto_20200204_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationsnum',
            options={'verbose_name': 'активація номера', 'verbose_name_plural': 'активація номерів'},
        ),
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 17, 9, 28, 777863)),
        ),
    ]
