# Generated by Django 3.0.2 on 2020-02-08 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0012_auto_20200208_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 18, 16, 6, 669641)),
        ),
    ]
