# Generated by Django 3.0.2 on 2020-02-08 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberops', '0015_auto_20200208_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationsnum',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 18, 20, 35, 235904)),
        ),
    ]
