# Generated by Django 3.0.2 on 2020-02-04 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'організація',
                'verbose_name_plural': 'організації',
            },
        ),
        migrations.CreateModel(
            name='UserNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=10, verbose_name='ІПН')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('patronymic', models.CharField(max_length=40, verbose_name='По батькові')),
                ('surname', models.CharField(max_length=40, verbose_name='Прізвище')),
                ('company', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='userinfo.OrgInfo', verbose_name='Організація')),
            ],
            options={
                'verbose_name': 'абонент',
                'verbose_name_plural': 'абоненти',
            },
        ),
    ]
