# Generated by Django 3.0.2 on 2020-02-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.OrgInfo', verbose_name='Організація'),
        ),
    ]
