# Generated by Django 3.0.2 on 2020-02-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20200204_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='inn',
            field=models.CharField(max_length=10, unique=True, verbose_name='ІПН'),
        ),
    ]
