# Generated by Django 3.0.2 on 2020-02-04 01:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Назва тарифу')),
                ('opname', models.CharField(choices=[(None, "Виберіть оператора зв'язку"), ('ks', 'Київстар'), ('vf', 'Водафон'), ('lf', 'Life:)'), ('it', 'Інтертелеком')], default=None, max_length=2, verbose_name='Мобільний оператор')),
                ('MbInTax', models.IntegerField(default=0, verbose_name='К-кість Mb в тарифі')),
                ('MbOffTax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість Mb поза тарифом')),
                ('MinInTax', models.IntegerField(default=0, verbose_name='Кількість хв. в мережі в тарифі')),
                ('MinOffTax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість хв. в мережі поза дарифом')),
                ('MinInTaxOther', models.IntegerField(default=0, verbose_name='Кількість хв. на інші мережі в тарифі')),
                ('MinOffTaxOther', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість хв. на інші мережі поза дарифом')),
                ('SmsOnTax', models.IntegerField(default=0, verbose_name='Кількість СМС в тарифі')),
                ('SmsOffTax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість СМС поза тарифом')),
                ('MmsOnTax', models.IntegerField(default=0, verbose_name='Кількість MМС в тарифі')),
                ('MmsOffTax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість MМС поза тарифом')),
            ],
            options={
                'verbose_name': 'тарифний план',
                'verbose_name_plural': 'тарифні плани',
            },
        ),
        migrations.CreateModel(
            name='NumMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введіть номер телефону', max_length=128, region=None, unique=True, verbose_name='Номер')),
                ('TaxMob', models.ForeignKey(default='+380991111111', on_delete=django.db.models.deletion.PROTECT, to='mobinfo.TaxMob', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'мобільний номер',
                'verbose_name_plural': 'мобільні номери',
            },
        ),
    ]
