# Generated by Django 3.0.2 on 2020-02-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20200204_0347'),
        ('mobinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsRah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRah', models.CharField(max_length=6)),
                ('OrgInfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.OrgInfo', verbose_name='Організація')),
            ],
        ),
    ]
