# Generated by Django 3.0.2 on 2020-02-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobinfo', '0002_osrah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osrah',
            options={'verbose_name': 'особовий рахунок', 'verbose_name_plural': 'особові рахунки'},
        ),
        migrations.AlterField(
            model_name='osrah',
            name='numRah',
            field=models.CharField(max_length=6, verbose_name='Особовий рахунок'),
        ),
    ]
